# -*- coding: utf-8 -*-
"""
Generic Approval Sheet Generator.

Produces a standardised multi-page A4-portrait approval PDF
usable for ANY customer and label type.

Layout (per page):
  ┌────────────────────────────────────────────────┐
  │  [NAVY HEADER]  Customer | Order | Date | N    │
  ├─────────┬─────────┬─────────────────────────────┤
  │ [label] │ [label] │ [label]                      │
  │  SKU-1  │  SKU-2  │  SKU-3                       │
  ├─────────┼─────────┼─────────────────────────────┤
  │ [label] │ [label] │ [label]                      │
  │  SKU-4  │  SKU-5  │  SKU-6                       │
  ├────────────────────────────────────────────────┤
  │ Artwork Engine  |  Job ID: xxxx  |  Page 1/N   │
  └────────────────────────────────────────────────┘

This is separate from the OVS-specific approval_pdf_service.py
which uses a custom A3-landscape layout for that customer.

Usage:
    from backend.services.approval_sheet import build_approval_sheet

    build_approval_sheet(
        job_id="abc12345",
        customer_code="ZARA",
        order_ref="ORDER-001",
        label_renders=[{"sku": "SKU-001", "thumb": <bytes>}, ...],
        output_path="output/abc12345/approval_sheet.pdf"
    )
"""
from datetime import date
from pathlib import Path

import fitz  # PyMuPDF

# ── Fixed A4 page constants ──────────────────────────────────────────────────
A4_W     = 595.0
A4_H     = 842.0
COLS     = 3
ROWS     = 2
MARGIN   = 28.0
HEADER_H = 60.0
FOOTER_H = 30.0
CELL_PAD = 10.0

# Derived layout
_USABLE_W = A4_W  - 2 * MARGIN
_USABLE_H = A4_H  - HEADER_H - FOOTER_H - 2 * MARGIN
_CELL_W   = (_USABLE_W - (COLS - 1) * CELL_PAD) / COLS
_CELL_H   = (_USABLE_H - (ROWS - 1) * CELL_PAD) / ROWS

# Colours
_NAVY  = (0.08, 0.14, 0.28)
_WHITE = (1.00, 1.00, 1.00)
_LGREY = (0.70, 0.70, 0.70)
_MGREY = (0.40, 0.40, 0.40)
_DARK  = (0.10, 0.10, 0.10)


def _draw_header(page: fitz.Page, customer_code: str, order_ref: str, total: int) -> None:
    """Draw the fixed navy header band."""
    page.draw_rect(
        fitz.Rect(0, 0, A4_W, HEADER_H),
        fill=_NAVY, color=None, width=0,
    )
    line1 = f"Customer: {customer_code}   |   Order: {order_ref}   |   Date: {date.today().isoformat()}   |   Labels: {total}"
    page.insert_text(
        fitz.Point(MARGIN, HEADER_H / 2 + 4),
        line1, fontname="hebo", fontsize=8.5, color=_WHITE,
    )
    page.insert_text(
        fitz.Point(MARGIN, HEADER_H / 2 + 17),
        "ARTWORK FOR APPROVAL",
        fontname="helv", fontsize=7.5, color=(0.8, 0.8, 0.8),
    )


def _draw_footer(page: fitz.Page, job_id: str, page_num: int, total_pages: int) -> None:
    """Draw the footer line with job ID and page number."""
    footer_y = A4_H - FOOTER_H + 10
    page.draw_line(
        fitz.Point(MARGIN, A4_H - FOOTER_H),
        fitz.Point(A4_W - MARGIN, A4_H - FOOTER_H),
        color=_LGREY, width=0.5,
    )
    page.insert_text(
        fitz.Point(MARGIN, footer_y),
        f"Generated by Artwork Engine  |  Job ID: {job_id}",
        fontname="helv", fontsize=7, color=_MGREY,
    )
    page_txt = f"Page {page_num} of {total_pages}"
    tw = fitz.get_text_length(page_txt, fontname="helv", fontsize=7)
    page.insert_text(
        fitz.Point(A4_W - MARGIN - tw, footer_y),
        page_txt, fontname="helv", fontsize=7, color=_MGREY,
    )


def build_approval_sheet(
    job_id:        str,
    customer_code: str,
    order_ref:     str,
    label_renders: list[dict],   # each: {"sku": str, "thumb": bytes}
    output_path:   str,
) -> None:
    """
    Build a standardised multi-page approval PDF in A4 portrait format.

    Args:
        job_id:        Unique job identifier for the footer.
        customer_code: Customer name/code for the header.
        order_ref:     Order reference for the header.
        label_renders: List of {"sku": str, "thumb": bytes} dicts.
                       thumb should be a PNG rendered at 60–150 DPI.
        output_path:   Where to save the output PDF.
    """
    doc         = fitz.open()
    total       = len(label_renders)
    per_page    = COLS * ROWS
    total_pages = max(1, (total + per_page - 1) // per_page)

    for page_num in range(1, total_pages + 1):
        page = doc.new_page(width=A4_W, height=A4_H)

        # White background
        page.draw_rect(fitz.Rect(0, 0, A4_W, A4_H), fill=_WHITE, color=None, width=0)

        # Header + footer
        _draw_header(page, customer_code, order_ref, total)
        _draw_footer(page, job_id, page_num, total_pages)

        # Label grid
        start = (page_num - 1) * per_page
        for idx, render in enumerate(label_renders[start: start + per_page]):
            col = idx % COLS
            row = idx // COLS

            cx = MARGIN + col * (_CELL_W + CELL_PAD)
            cy = HEADER_H + MARGIN + row * (_CELL_H + CELL_PAD)
            cell_rect = fitz.Rect(cx, cy, cx + _CELL_W, cy + _CELL_H)

            # Cell border
            page.draw_rect(cell_rect, color=_LGREY, fill=None, width=0.5)

            # Thumbnail image
            thumb = render.get("thumb")
            if thumb:
                page.insert_image(cell_rect, stream=thumb)

            # SKU label below cell
            sku = render.get("sku", "")
            if sku:
                page.insert_text(
                    fitz.Point(cx, cy + _CELL_H + 8),
                    sku, fontname="helv", fontsize=6, color=_DARK,
                )

    # Ensure at least one page
    if not doc.page_count:
        doc.new_page(width=A4_W, height=A4_H)

    # Save
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    doc.save(output_path, garbage=4, deflate=True)
    doc.close()
