import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Download, ArrowLeft, ChevronLeft, ChevronRight, RefreshCw } from 'lucide-react';
import { getApprovalSheetData, approvalSheetPdfUrl, approvalSheetPagePngUrl } from '../api/client';

/**
 * ApprovalPreview — shows each page of the approval-sheet PDF as a
 * server-rendered PNG image.  The preview is pixel-identical to the
 * downloadable PDF because both are generated by the same backend code.
 */
export default function ApprovalPreview() {
  const { orderId, artworkId } = useParams();
  const navigate = useNavigate();

  // Meta from the approval-sheet data API (for page labels / navigation)
  const [meta,       setMeta]       = useState(null);
  const [metaError,  setMetaError]  = useState('');
  const [activePage, setActivePage] = useState(0);

  // Image state for the current page
  const [imgSrc,     setImgSrc]     = useState('');
  const [imgLoading, setImgLoading] = useState(true);
  const [imgError,   setImgError]   = useState('');
  const [imgKey,     setImgKey]     = useState(0);   // bump to force reload

  // ── Fetch meta once ────────────────────────────────────────────────────────
  useEffect(() => {
    getApprovalSheetData(artworkId)
      .then(res => setMeta(res.data))
      .catch(err => {
        const detail = err?.response?.data?.detail || err.message || 'Unknown error';
        setMetaError(detail);
      });
  }, [artworkId]);

  // ── Rebuild image URL whenever page changes ────────────────────────────────
  useEffect(() => {
    setImgLoading(true);
    setImgError('');
    // 150 dpi gives a clear screen render at ~2480px wide for A3
    setImgSrc(approvalSheetPagePngUrl(artworkId, activePage, 150));
  }, [artworkId, activePage]);

  const groups     = meta?.country_groups || [];
  const totalPages = groups.length || (meta ? 1 : 0);

  const handleImgLoad  = () => setImgLoading(false);
  const handleImgError = () => {
    setImgLoading(false);
    setImgError('Could not load page image — the server may still be generating it.');
  };

  const reload = () => {
    setImgLoading(true);
    setImgError('');
    setImgKey(k => k + 1);
    setImgSrc(approvalSheetPagePngUrl(artworkId, activePage, 150) + `&_r=${Date.now()}`);
  };

  return (
    <div>
      {/* ── Action bar ── */}
      <div className="page-header" style={{ marginBottom: '20px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>

          <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
            <button className="btn btn-ghost" onClick={() => navigate(`/orders/${orderId}`)}>
              <ArrowLeft size={16} /> Back to Order
            </button>
            <div>
              <h1 style={{ fontSize: '18px', margin: 0 }}>Approval Preview</h1>
              <p style={{ margin: 0, fontSize: '13px', opacity: 0.7 }}>
                {meta?.bgp_order_id || '…'}
                {totalPages > 0 && ` — ${totalPages} market group${totalPages !== 1 ? 's' : ''}`}
              </p>
            </div>
          </div>

          <div style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
            <button className="btn btn-ghost btn-sm" onClick={reload} title="Reload page">
              <RefreshCw size={14} />
            </button>
            <a
              href={approvalSheetPdfUrl(artworkId)}
              download
              className="btn btn-primary"
            >
              <Download size={16} /> Download Full PDF
            </a>
          </div>
        </div>

        {/* Page switcher — driven by groups from meta */}
        {totalPages > 1 && (
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginTop: '16px' }}>
            <button className="btn btn-ghost btn-sm"
              disabled={activePage === 0}
              onClick={() => setActivePage(p => p - 1)}>
              <ChevronLeft size={14} /> Prev
            </button>

            {groups.map((g, i) => (
              <button key={i}
                className={`btn btn-sm ${i === activePage ? 'btn-primary' : 'btn-ghost'}`}
                onClick={() => setActivePage(i)}
                style={{ minWidth: '90px' }}>
                {g.country}
              </button>
            ))}

            <button className="btn btn-ghost btn-sm"
              disabled={activePage === totalPages - 1}
              onClick={() => setActivePage(p => p + 1)}>
              Next <ChevronRight size={14} />
            </button>
          </div>
        )}
      </div>

      {/* ── Error states ── */}
      {metaError && (
        <div className="alert alert-error" style={{ marginBottom: '16px' }}>
          ⚠ {metaError}
        </div>
      )}

      {/* ── PDF page rendered as PNG ── */}
      <div style={{
        background: '#e0e0e0',
        padding: '24px',
        borderRadius: '8px',
        overflowX: 'auto',
        minHeight: '400px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      }}>

        {/* Loading spinner overlay */}
        {imgLoading && (
          <div style={{
            display: 'flex', flexDirection: 'column',
            alignItems: 'center', justifyContent: 'center',
            padding: '60px', gap: '12px',
          }}>
            <div className="spinner" style={{ width: 36, height: 36 }} />
            <p className="text-muted" style={{ margin: 0 }}>Rendering page {activePage + 1}…</p>
            <p style={{ margin: 0, fontSize: '12px', color: '#999' }}>
              First load may take ~10s while the server wakes up.
            </p>
          </div>
        )}

        {/* Error state */}
        {imgError && !imgLoading && (
          <div style={{ textAlign: 'center', padding: '40px' }}>
            <div className="alert alert-error" style={{ marginBottom: '16px' }}>⚠ {imgError}</div>
            <button className="btn btn-ghost" onClick={reload}>
              <RefreshCw size={14} /> Try again
            </button>
          </div>
        )}

        {/* The page image — always rendered so onLoad/onError fire correctly */}
        {imgSrc && (
          <img
            key={imgKey}
            src={imgSrc}
            alt={`Approval sheet page ${activePage + 1}`}
            onLoad={handleImgLoad}
            onError={handleImgError}
            style={{
              display: imgLoading || imgError ? 'none' : 'block',
              maxWidth: '100%',
              boxShadow: '0 4px 32px rgba(0,0,0,0.22)',
              borderRadius: '2px',
              background: 'white',
            }}
          />
        )}

        {/* Page indicator */}
        {!imgLoading && !imgError && (
          <div style={{ marginTop: '12px', color: '#666', fontSize: '12px' }}>
            Page {activePage + 1} of {Math.max(totalPages, 1)}
          </div>
        )}
      </div>
    </div>
  );
}
